baseURL = 'https://portfolio-robo358.netlify.app/'
title = 'Tsuru-Portfolio|ãƒãƒ¼ãƒˆãƒ•ã‚©ãƒªã‚ª'
copyright = '@ROBO358'
theme = 'lightbi-hugo'

languageCode = 'ja'
defaultContentLanguage = 'ja'
hasCJKLanguage = true

[Params]
socialShare = true
authorInfo = "ã¤ã‚‹ã‚‹ã‚“ğŸ¥•@ROBO358"
description="ROBO358ãŒä½œæˆã—ãŸä½œå“ã‚’ã¾ã¨ã‚ãŸ"

[Author]
  name = "TSURUDO, Ryosuke"
  website = "https://ROBO358.com/"
  email = "rroobboo.358@gmail.com"
#  facebook = "username"
#  instagram = "username"
#  youtube = "user/username" # or channel/channelname
  twitter = "ROBO358"
#  threads = "username"
#  linkedin = "username"
  github = "ROBO358"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags/blog/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
